# Generated by Django 4.0.1 on 2022-01-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last name')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add date')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appear_date', models.DateTimeField(auto_now_add=True, verbose_name='appear date')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('rating', models.FloatField(default=0, verbose_name='rating')),
                ('cover_material', models.CharField(choices=[('HC', 'hardcover'), ('PB', 'paperback')], max_length=20, verbose_name='cover material')),
                ('image', models.ImageField(upload_to='books', verbose_name='image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.author', verbose_name='author')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.genre', verbose_name='genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
