# Generated by Django 4.0.1 on 2022-01-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting for payment', 'Waiting For Payment'), ('In deliver', 'Delivering'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Returned', 'Returned')], default='Waiting for payment', max_length=25, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_material',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback')], max_length=20, verbose_name='cover material'),
        ),
    ]
