# Generated by Django 4.0.1 on 2022-01-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_address_order_status_alter_book_cover_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_year',
            field=models.PositiveIntegerField(null=True, verbose_name='release year'),
        ),
    ]
